Description: Base template for user to be used in LambFormation pipeline
Parameters:
  UserName:
    Type: String
Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      Tags:
        - Key: UserType
          Value: UseCaseUser