AWSTemplateFormatVersion: '2010-09-09'
Description: Base template for user to be used in LambFormation pipeline
Parameters:
  UserName:
    Type: String
Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        # assigning this value should be automated in long term solution
        Password: initialPasswordForUserToLoginIntoPlatform
        PasswordResetRequired: true
      Groups:
        - !ImportValue BaseUseCaseUserGroup
      Tags:
        - Key: UserType
          Value: UseCaseUser