AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31 
Globals:
  Function:
    Runtime: python3.7
    MemorySize: 128
    Timeout: 900
    Handler: index.lambdaHandler
    Environment:
      Variables:
        TEMPLATE_BUCKET: lambformation-demo
        REPOSITORY_NAME: !GetAtt UseCaseStateRepository.Name
        STATE_FILE: lambformation-demo
        CREATE_USER_LAMBDA: 'lambformation-createUser'
        DELETE_USER_LAMBDA: 'lambformation-deleteUser'
        CREATE_USECASE_LAMBDA: 'lambformation-createUseCase'
        UPDATE_USECASE_LAMBDA: 'lambformation-updateUseCase'
        DELETE_USECASE_LAMBDA: 'lambformation-deleteUseCase'
        USER_STACK_PREFIX: 'lambformation-user'
        USE_CASE_STACK_PREFIX: 'lambformation-useCase'
        USER_TEMPLATE_URL: 'https://lambformation-demo.s3.eu-central-1.amazonaws.com/baseUser.yaml'
        USE_CASE_TEMPLATE_URL: 'https://lambformation-demo.s3.eu-central-1.amazonaws.com/useCaseBase.yaml'
Resources:
  PrepareChangeset:
    Type: AWS::Serverless:Function
    Properties:
      CodeUri: lambda/prepareChangeset
      Description: Lambda function to prepare changeset for useCases
      FunctionName: lambformation-prepareChangeset
      Role: !GetAtt UseCasePipelineLambdaRole.Arn
  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/createUser
      Description: Lambda function to create users
      FunctionName: lambformation-createUser
    Role: !Ref CommonLambFormationLambdaRole
  DeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/deleteUser
      Description: Lambda function to delete users
      FunctionName: lambformation-deleteUser
    Role: !Ref CommonLambFormationLambdaRole
  CreateUseCase:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/createUseCase
      Description: Lambda function to create useCases
      FunctionName: lambformation-createUseCase
    Role: !Ref CommonLambFormationLambdaRole
  UpdateUseCase:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/updateUseCase
      Description: Lambda function to update useCases
      FunctionName: lambformation-updateUseCase
      Role: !Ref CommonLambFormationLambdaRole
  DeleteUseCase:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/deleteUseCase
      Description: Lambda function to delete useCases
      FunctionName: lambformation-deleteUseCase
      Role: !Ref CommonLambFormationLambdaRole
  CommonLambFormationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17 
        Statement: 
          - Effect: Allow 
            Principal: 
              Service: 
                - lambda.amazonaws.com 
            Action: 
              - 'sts:AssumeRole' 
      Policies: 
        - PolicyName: AA-UseCasePipelineLambdaPolicy 
          PolicyDocument: 
            Version: 2012-10-17 
            Statement: 
              - 
                Sid: CodeCommitAccess 
                Effect: Allow 
                Action:  
                  - codecommit:GetBranch 
                  - codecommit:GetCommit 
                  - codecommit:GetBlob 
                  - codecommit:GetDifferences 
                  - codecommit:GetFile 
                  - codecommit:GetRepository 
                Resource: !GetAtt UseCaseStateRepository.Arn 
              - 
                Sid: CloudFormationAccess 
                Effect: Allow 
                Action: 
                  - cloudformation:CreateStack 
                  - cloudformation:ValidateTemplate 
                  - cloudformation:ListExports 
                  - cloudformation:ListStacks 
                  - cloudformation:DescribeStacks 
                  - cloudformation:DescribeStackEvents 
                  - cloudformation:DeleteStack 
                  - cloudformation:UpdateStack 
                  - cloudformation:DescribeStackResources 
                  - cloudformation:GetTemplate 
                Resource: "*" 
              - 
                Sid: CloudWatchAccess 
                Effect: Allow 
                Action: 
                  - logs:PutLogEvents 
                Resource: 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lambformation-prepareChangeset:*:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lambformation-createUseCase:*:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lambformation-deleteUseCase:*:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lambformation-updateUseCase:*:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lambformation-createUser:*:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/lambformation-deleteUser:*:*'
              - 
                Sid: CloudWatchLogStream 
                Effect: Allow 
                Action: 
                  - logs:CreateLogStream 
                  - logs:TagLogGroup 
                  - logs:CreateLogGroup 
                Resource: "*" 
              - 
                Sid: InvokeLambdaAccess 
                Effect: Allow 
                Action: 
                  - lambda:InvokeAsync 
                  - lambda:InvokeFunction 
                Resource: 
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambformation-createUseCase'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambformation-updateUseCase'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambformation-deleteUseCase'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambformation-prepareChangeset'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambformation-createUser'
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambformation-deleteUser'
              - 
                Sid: s3Access
                Effect: Allow
                Action: 
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:CreateBucketPolicy
                  - s3:DeleteBucketPolicy
                  - s3:ListBuckets
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - 
                Sid: IAMAccess
                Effect: Allow
                Action: 
                  - iam:*
                Resource: "*"
              - 
                Sid: ServiceCatalogAccess
                Effect: Allow
                Action:
                  - serviceCatalog:*
  UseCaseStateRepository:
    Type: AWS::CodeCommitRepository
    Properties: 
      RepositoryDescription: Repository to track State for resources
      RepositoryName: lambformation-state
  CodeCommitCloudWatchEventRule: 
    Type: AWS::Events::Rule 
    Properties: 
      EventPattern: 
        source: 
          - aws.codecommit 
        detail-type: 
          - 'CodeCommit Repository State Change' 
        resources: 
          - !GetAtt UseCaseStateRepository.Arn 
        detail: 
          event: 
            - referenceCreated 
            - referenceUpdated 
          referenceType: 
            - branch 
          referenceName: 
            - master 
      Targets: 
        - 
          Arn: !GetAtt PrepareChangeset.Arn 
          Id: lambformation-prepareChangeset
  EventPermissionToInvokeLambda: 
    Type: AWS::Lambda::Permission 
    Properties:  
      Action: lambda:InvokeFunction 
      FunctionName: !Ref PrepareChangeset  
      Principal: 'events.amazonaws.com' 
      SourceArn: !GetAtt CodeCommitCloudWatchEventRule.Arn