AWSTemplateFormatVersion: 2010-09-09
Parameters:
  UseCaseName:
    Type: String
  Users:
    Type: List<String>
Resources:
  UseCaseGroup:
    Description: UseCaseUser group to later attach users
    Type: AWS::IAM::Group
    Properties: 
      GroupName: !Sub "${UseCaseName}-UserGroup"
      ManagedPolicyArns: 
        - !Ref UseCaseUserPolicy
      Path: /
  UseCaseUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: String
      ManagedPolicyName: !Sub "${UseCaseName}-UserPolicy"
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:DeleteBucket
            Effect: Deny
            Resource: "*"