AWSTemplateFormatVersion: 2010-09-09
Parameters:
  UseCaseName:
    Type: String
  Users:
    Type: List<String>
  UsersExist:
    Type: String
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"
Conditions:
  CreateUserAttachment: !Not [!Equals [!Ref UsersExist, "no"]]
Resources:
  UseCaseGroup:
    Description: UseCaseUser group to later attach users
    Type: AWS::IAM::Group
    Properties: 
      GroupName: !Sub "${UseCaseName}-UserGroup"
      ManagedPolicyArns: 
        - !Ref UseCaseUserPolicy
      Path: /
  UsersAttachment:
    Type: AWS::IAM::UserToGroupAddition
    Condition: CreateUserAttachment
    Properties: 
      GroupName: !Ref UseCaseGroup
      Users: !Ref Users
  UseCaseUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: String
      ManagedPolicyName: !Sub "${UseCaseName}-UserPolicy"
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:DeleteBucket
            Effect: Deny
            Resource: "*"