AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  UseCaseName:
    Type: String
  Users:
    Type: List<String>
Resources:
  UseCaseIamUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub ${UseCaseName}-UserGroup
      Path: /
      Policies: 
        - !Ref UseCaseUserPolicy
  UseCaseRole:
    Description: UseCaseUser group to later attach users
    Type: AWS::IAM::Role
  UseCaseInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub ${UseCaseName}-instance
      Path: /
      Roles: 
        - !Ref UseCaseInstanceRole
  UseCaseUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: String
      ManagedPolicyName: !Sub ${UseCaseName}-UserPolicy
      Path: /
      PolicyDocument: 
        # Fill in YAML format
      Roles: 
        - String
      Users: 
        - !Ref Users
  UseCaseBucket:
    Description: S3Bucket for useCaseData
    Type: AWS::S3::Bucket
  UseCasePortfolio:
    Type: AWS::ServiceCatalog::Portfolio
  UseCaseProduct:
    Type: AWS::ServiceCatalog::Product
  


